import { redirect as nextRedirect } from "next/navigation";
import { requirePageRole } from "../../lib/auth/require-role";
import { createClient as createSupabaseClient } from "../../lib/supabase/server";
type State={status?:"error";message?:string};
export type ModerationDependencies={createClient:()=>Promise<{from:(t:"posts")=>{update:(v:{is_notice:boolean})=>{eq:(c:"id",v:string)=>{select:(c:"id")=>Promise<{data:{id:string}[]|null;error:unknown}>}};delete:()=>{eq:(c:"id",v:string)=>{select:(c:"id")=>Promise<{data:{id:string}[]|null;error:unknown}>}}}}>;redirect:(p:string)=>never;requirePageRole:(r:"member",o:{nextPath:string})=>Promise<{id:string;role:"member"|"admin"}>};
const defaults:ModerationDependencies={createClient:async()=>await createSupabaseClient() as unknown as Awaited<ReturnType<ModerationDependencies["createClient"]>>,redirect:nextRedirect,requirePageRole};
const forbidden={status:"error" as const,message:"이 작업을 수행할 권한이 없습니다."};
export function toggleNoticeAction(id:string,is_notice:boolean,d=defaults){return async():Promise<State>=>{"use server";const p=await d.requirePageRole("member",{nextPath:`/board/${id}`});if(p.role!=="admin")return forbidden;try{const r=await(await d.createClient()).from("posts").update({is_notice}).eq("id",id).select("id");if(r.error||!r.data?.length)return{status:"error",message:"공지를 변경하지 못했습니다. 잠시 후 다시 시도해 주세요."}}catch{return{status:"error",message:"공지를 변경하지 못했습니다. 잠시 후 다시 시도해 주세요."}}return d.redirect(`/board/${id}`)}}
export function deletePostAction(id:string,d=defaults){return async():Promise<State>=>{"use server";const p=await d.requirePageRole("member",{nextPath:`/board/${id}`});if(p.role!=="admin")return forbidden;try{const r=await(await d.createClient()).from("posts").delete().eq("id",id).select("id");if(r.error||!r.data?.length)return{status:"error",message:"게시글을 삭제하지 못했습니다. 잠시 후 다시 시도해 주세요."}}catch{return{status:"error",message:"게시글을 삭제하지 못했습니다. 잠시 후 다시 시도해 주세요."}}return d.redirect("/board")}}
